[package]
name = "depy"
version = "0.1.0"
edition = "2021"

[dependencies]
copy_dir = "0.1.3"
duct = "0.13"
fs_extra = "1.3.0"
path-absolutize = "3.1.1"
serde_json = "1.0.117"
thiserror = "1.0.60"
ureq = "2.9.7"
